<?php

declare(strict_types=1);

use Drupal\Component\Serialization\Yaml;
use Drupal\webform\Entity\Webform;

$path = $extra[0] ?? (__DIR__ . '/data/frontend-content.growbig.json');

if (!is_file($path)) {
  throw new RuntimeException("Frontend content data file not found: {$path}");
}

$payload = json_decode((string) file_get_contents($path), TRUE);

if (!is_array($payload)) {
  throw new RuntimeException("Invalid frontend content JSON: {$path}");
}

foreach (($payload['forms'] ?? []) as $form) {
  $webform_id = $form['webformId'] ?? '';
  $title = $form['title'] ?? $webform_id;

  if (!$webform_id || empty($form['webformElements']) || !is_array($form['webformElements'])) {
    continue;
  }

  $webform = Webform::load($webform_id);

  if (!$webform) {
    $webform = Webform::create([
      'id' => $webform_id,
      'title' => $title,
      'status' => 'open',
    ]);
  }

  $webform->set('title', $title);
  $webform->set('description', $form['description'] ?? '');
  $webform->set('status', 'open');
  $webform->set('elements', Yaml::encode($form['webformElements']));
  $webform->set('settings', [
    'confirmation_type' => 'message',
    'confirmation_message' => $form['successMessage'] ?? 'Submission received.',
  ]);

  if (!empty($form['notification']['enabled'])) {
    $notification = $form['notification'];
    $handler_id = 'frontend_email_notification';
    $to_mail = trim((string) ($notification['to'] ?? ''));

    if ($to_mail !== '') {
      $subject = (string) ($notification['subject'] ?? 'New website form submission');
      $subject = str_replace('[form:title]', '[webform:title]', $subject);
      $subject = preg_replace('/\\[submission:([^\\]]+)\\]/', '[webform_submission:values:$1]', $subject);

      $intro = (string) ($notification['intro'] ?? 'A new website form submission has been received.');

      $handlers = $webform->get('handlers') ?: [];
      $handlers[$handler_id] = [
        'id' => 'email',
        'handler_id' => $handler_id,
        'label' => 'Frontend email notification',
        'notes' => '',
        'status' => TRUE,
        'conditions' => [],
        'weight' => 0,
        'settings' => [
          'states' => ['completed'],
          'to_mail' => $to_mail,
          'to_options' => [],
          'cc_mail' => '',
          'cc_options' => [],
          'bcc_mail' => '',
          'bcc_options' => [],
          'from_mail' => '[site:mail]',
          'from_options' => [],
          'from_name' => '[site:name]',
          'reply_to' => '[webform_submission:values:email:raw]',
          'return_path' => '',
          'sender_mail' => '',
          'sender_name' => '',
          'subject' => $subject,
          'body' => '<div style="font-family:Arial,sans-serif;color:#0f172a;line-height:1.5;">'
            . '<h2 style="margin:0 0 12px;">[webform:title]</h2>'
            . '<p style="margin:0 0 16px;">' . htmlspecialchars($intro, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8') . '</p>'
            . '<p style="margin:0 0 16px;color:#64748b;">Submission ID: [webform_submission:sid]</p>'
            . '<div style="padding:16px;border:1px solid #e5e7eb;background:#f8fafc;">[webform_submission:values]</div>'
            . '<p style="margin-top:20px;color:#64748b;font-size:13px;">This notification was generated by the Drupal Webform email handler.</p>'
            . '</div>',
          'excluded_elements' => [],
          'ignore_access' => FALSE,
          'exclude_empty' => TRUE,
          'exclude_empty_checkbox' => FALSE,
          'exclude_attachments' => FALSE,
          'html' => TRUE,
          'attachments' => FALSE,
          'twig' => FALSE,
          'theme_name' => '',
          'parameters' => [],
          'debug' => FALSE,
        ],
      ];

      $webform->set('handlers', $handlers);
    }
  }

  $webform->save();

  print "Saved webform: {$webform_id}\n";
}

\Drupal::state()->set('site_platform.frontend_payload', $payload);

\Drupal::configFactory()->getEditable('system.site')
  ->set('name', $payload['site']['name'] ?? 'Drupal Decoupled Backend')
  ->set('mail', $payload['site']['email'] ?? '')
  ->save(TRUE);

\Drupal::configFactory()->getEditable('site_platform.runtime')
  ->set('mode', 'single_backend')
  ->set('frontend_count', 1)
  ->set('multisite_supported', FALSE)
  ->set('domain_required', FALSE)
  ->save(TRUE);

drupal_flush_all_caches();

print "Seeded generic frontend payload from: {$path}\n";
print "Project key: " . ($payload['template']['projectKey'] ?? 'unknown') . "\n";
print "Frontend payload seeded. Media references are read from the project JSON payload.\n";
